import { sessionKeyForAgent } from './session-key'
import type { GatewaySessionRow } from './session-types'

export const DEFAULT_NEW_SESSION_LABEL = 'Chat New Session'

/** Placeholder labels from "New session" before auto-title runs. */
export function isPlaceholderSessionLabel(label: string): boolean {
  const t = label.trim()
  if (!t) return false
  if (t === DEFAULT_NEW_SESSION_LABEL) return true
  return /^Chat New Session \d+$/.test(t)
}

/** Pick a gateway-unique label for a new dashboard session. */
export function allocateNewSessionLabel(
  sessions: GatewaySessionRow[],
  agentId: string,
): string {
  const used = new Set<string>()
  for (const row of sessions) {
    if (!row.key || !isBrowsableChatSession(row.key, agentId)) continue
    used.add(resolveSessionDisplayName(row.key, row))
  }
  if (!used.has(DEFAULT_NEW_SESSION_LABEL)) return DEFAULT_NEW_SESSION_LABEL
  let n = 2
  while (used.has(`${DEFAULT_NEW_SESSION_LABEL} ${n}`)) n += 1
  return `${DEFAULT_NEW_SESSION_LABEL} ${n}`
}

/** Gateway fallback title from session UUID prefix, e.g. "e7a6cc00 (2026-06-05)". */
function isAutoGeneratedSessionTitle(title: string): boolean {
  return /^[0-9a-f]{8}( \(\d{4}-\d{2}-\d{2}\))?$/i.test(title.trim())
}

function normalizeAgentId(agentId: string): string {
  return agentId.trim().toLowerCase() || 'main'
}

/** True for main + dashboard webchat sessions of the given agent. */
export function isBrowsableChatSession(sessionKey: string, agentId: string): boolean {
  const key = sessionKey.trim().toLowerCase()
  const id = normalizeAgentId(agentId)
  const prefix = `agent:${id}:`
  if (!key.startsWith(prefix)) return false
  const rest = key.slice(prefix.length)
  return rest === 'main' || rest.startsWith('dashboard:')
}

export function resolveSessionDisplayName(key: string, row?: GatewaySessionRow): string {
  const label = row?.label?.trim() ?? ''
  const displayName = row?.displayName?.trim() ?? ''
  const derivedTitle = row?.derivedTitle?.trim() ?? ''

  if (label && label !== key) return label
  if (displayName && displayName !== key) return displayName
  if (
    derivedTitle &&
    derivedTitle !== key &&
    !isAutoGeneratedSessionTitle(derivedTitle)
  ) {
    return derivedTitle
  }

  const normalized = key.toLowerCase()
  if (normalized === 'main' || normalized === 'agent:main:main') {
    return 'Main session'
  }

  const dashboardMatch = normalized.match(/^agent:[^:]+:dashboard:/)
  if (dashboardMatch) {
    return DEFAULT_NEW_SESSION_LABEL
  }

  return key
}

function mergeLabelOverrides(
  sessions: GatewaySessionRow[],
  labelOverrides: ReadonlyMap<string, string>,
): GatewaySessionRow[] {
  if (labelOverrides.size === 0) return sessions
  return sessions.map((row) => {
    const patched = labelOverrides.get(row.key)?.trim()
    if (!patched) return row
    const existing = row.label?.trim()
    if (existing && existing !== row.key) return row
    return { ...row, label: patched, displayName: patched }
  })
}

function mergeUpdatedAtOverrides(
  sessions: GatewaySessionRow[],
  updatedAtOverrides: ReadonlyMap<string, number | null>,
): GatewaySessionRow[] {
  if (updatedAtOverrides.size === 0) return sessions
  return sessions.map((row) => {
    if (!updatedAtOverrides.has(row.key)) return row
    return { ...row, updatedAt: updatedAtOverrides.get(row.key) ?? row.updatedAt }
  })
}

export type SessionListSidebarOptions = {
  labelOverrides?: ReadonlyMap<string, string>
  /** Keep sidebar order after label-only sessions.patch (gateway bumps updatedAt). */
  updatedAtOverrides?: ReadonlyMap<string, number | null>
}

export function filterSessionsForChatSidebar(
  sessions: GatewaySessionRow[],
  agentId: string,
  options?: SessionListSidebarOptions,
): GatewaySessionRow[] {
  let rows = sessions
  if (options?.labelOverrides) {
    rows = mergeLabelOverrides(rows, options.labelOverrides)
  }
  if (options?.updatedAtOverrides) {
    rows = mergeUpdatedAtOverrides(rows, options.updatedAtOverrides)
  }
  return rows
    .filter((row) => row.key && isBrowsableChatSession(row.key, agentId) && row.archived !== true)
    .toSorted((a, b) => (b.updatedAt ?? 0) - (a.updatedAt ?? 0))
}

/** Drop client-side overrides once gateway list includes the same label. */
export function reconcilePatchedSessionLabels(
  sessions: GatewaySessionRow[],
  labelOverrides: Map<string, string>,
): void {
  for (const row of sessions) {
    const patched = labelOverrides.get(row.key)?.trim()
    const fromGateway = row.label?.trim()
    if (patched && fromGateway === patched) {
      labelOverrides.delete(row.key)
    }
  }
}

export function isMainSessionKey(key: string, agentId: string): boolean {
  return key.trim().toLowerCase() === sessionKeyForAgent(agentId).toLowerCase()
}
